/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 08.01.2026 12:10:07

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,144 } };
const TfArray<1, float> quant0_scale = { 1, { 0.11448872834444046, } };
const TfArray<1, int> quant0_zero = { 1, { 24 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 69, -49, 5, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00042379306978546083, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  23, 13, 35, -87, -41, 1, 40, -87, -27, 39, 
  59, 25, 4, -52, -126, 36, 33, -50, -17, 9, 
  -41, -5, 33, 1, -68, -44, -127, -50, 42, 58, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0063231214880943298, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 0, 8, 8, -7, 29, 9, -9, -13, -9, 0, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00085412664338946342, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  6, -33, -20, 10, 31, 17, 36, -55, 7, -32, -66, 17, 23, 39, -5, -13, -6, 7, -46, -63, 
  -21, -33, 7, 15, 4, -2, -21, -33, -18, -5, -10, -6, 15, -2, 28, 22, -18, 16, -20, -4, 
  -14, -28, -9, 22, -20, -6, -18, -3, -7, -12, 11, 18, -2, -25, 9, -12, 10, -16, -38, -16, 
  4, -11, 23, -10, -42, 56, -20, -32, -18, 27, 127, 63, -12, -53, 18, 20, -12, 3, 57, 105, 
  -23, 47, -15, 10, -36, 30, -52, 8, -1, 23, 61, 38, 7, 29, 27, -19, -54, 38, 32, 26, 
  -38, 55, -12, 34, -16, -20, -12, 34, -26, -25, 25, 29, 10, 46, 8, -3, 1, 32, -40, 8, 
  58, 29, -3, 18, 41, 29, -13, -12, 28, -2, 27, 16, -2, -26, 24, -5, 17, 18, -13, 0, 
  -11, 49, 9, 16, -9, 61, 95, -62, 33, -25, -19, 62, 22, 16, -20, 68, 112, 34, -6, 104, 
  20, -2, 13, 19, 29, 22, -58, -23, 2, -4, 36, 17, -18, -48, 1, 35, -44, 30, -33, -9, 
  11, -29, -6, 8, 25, 36, -19, -2, 26, -45, -82, 24, -10, -26, -5, 6, -10, 33, -4, -27, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0065718023106455803, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -7, 2, 2, -2, -6, 1, -7, 1, -1, 4, 1, 2, -6, 1, 1, 0, -8, 1, 1, 1, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0019000759348273277, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*144] = { 
  -28, -30, 51, -10, 28, 11, 13, -3, 4, -12, 2, 9, -11, -14, -2, 9, 0, 7, 8, -47, 71, -25, -20, 3, -6, 11, -4, -3, -4, -6, 4, 2, 9, -7, -8, 7, -16, 71, 11, -37, 42, -5, -7, -3, -13, 4, -11, 5, -9, -11, -6, -11, 1, -5, -6, -21, -6, -8, 34, 20, 20, 4, 6, -4, 0, -5, 4, 12, 25, 4, 11, -3, -37, 2, -15, -16, 14, 4, -4, 11, -5, -8, -11, -4, -11, -4, -15, -7, -10, -6, 12, 17, -12, 12, -14, -9, 10, 3, -9, -6, -3, -9, -1, 2, -5, -5, -6, -1, 6, 21, 18, 3, 16, 7, -2, 13, -5, 2, -8, 2, 5, 0, 2, 10, -7, -2, 11, 38, 5, -18, 7, -6, 9, 2, 8, -5, 1, 10, -2, -2, 5, 2, -6, -2, 
  -22, -12, 64, -8, -76, -9, -4, -1, -7, 3, -13, -2, -8, -9, -1, -13, -1, -9, 15, -22, 23, -12, -66, -9, -1, -1, -9, 1, -7, -10, -7, 2, 4, 4, 1, -8, -3, 16, -17, 6, 55, -5, 15, 11, 3, -6, 3, -8, -2, -2, -11, -3, 0, -1, 4, 45, 4, 16, 106, -9, -3, 4, -7, -8, -9, -6, 2, -12, 2, -7, 7, -6, -5, -19, -6, -11, 0, -9, -6, 4, -9, -14, -14, -7, -5, -5, -7, -11, -3, 1, 12, 22, 42, 31, -14, 11, -1, -4, 4, -6, 4, 12, 2, 0, -4, 6, 9, -6, 8, -25, -30, 13, 81, 7, 1, 12, 4, 5, -4, -5, 6, -5, -1, -3, 4, -1, 10, -53, 25, 39, 57, -2, 6, -2, 11, 9, -2, 0, 3, 9, -5, 5, 1, -2, 
  -4, -4, -9, -8, 29, -4, 0, 0, 1, -3, -5, -3, -5, -1, -4, 0, -1, -1, 7, -3, -3, -9, 15, -1, 2, 1, 6, 4, 0, -1, 0, 4, 4, -1, 1, 1, 3, -3, -4, -8, -5, 3, -3, 0, 2, 0, -1, -2, 2, 0, 3, 0, 0, 0, 8, -7, -6, -5, -6, -1, 4, -1, 0, 1, -1, 3, 1, -1, 0, -1, 0, -3, 6, 2, -6, -8, -7, 3, -1, -2, 2, -2, 2, 0, 1, 1, -1, 0, -2, 1, 4, -3, -6, -6, 8, 6, 4, 5, 4, 4, -1, -1, 1, 0, 5, 1, 6, 6, 7, 21, -7, -4, -5, 0, 0, -1, 4, 7, 2, 4, 1, 6, 7, -1, 6, 6, 8, -3, -9, -6, -2, 0, 3, 4, 4, 4, 0, 5, 5, 4, 2, 6, 6, 6, 
  -8, 9, -11, -6, -9, 12, 7, 12, 12, 3, 13, 13, 11, 12, 11, 7, 3, 6, 11, 10, -11, -7, -9, 4, 10, 9, 2, 10, 12, 10, 3, 9, 12, 3, 10, 7, 12, -5, -7, -3, 3, 10, 6, 11, 14, 1, 6, 2, 10, 9, 2, 6, 4, 0, 9, 0, -12, -11, -2, 6, 15, 10, 15, 14, 3, 1, 13, 2, 3, 1, 12, 3, 5, 2, -8, -6, 0, 15, 10, 15, 9, 13, 14, 5, 6, 2, 6, 4, 13, 4, 12, -4, -10, -8, -2, 2, 1, 3, 10, 3, 3, 4, 10, 1, 2, 4, 5, 3, 11, -7, -10, -8, -5, 9, 5, 11, -1, 5, 9, 4, -1, 10, 5, 7, 0, 5, 10, -9, -8, -6, -2, -1, 3, 11, 3, 2, 1, 6, 5, 9, 9, 9, 6, 2, 
  -23, -25, 44, -19, 6, -11, 11, -1, -11, 1, -7, 0, -10, -12, -9, -3, -2, -3, 9, -44, 26, -16, -7, 0, 0, 2, 7, 8, -5, -4, 6, -5, 10, -4, -1, -2, -14, -18, 8, -27, 30, 0, -7, -4, -1, -11, -1, -2, -4, 1, 1, 3, -9, -4, -5, -9, -3, -10, 10, 11, 1, 1, 12, 11, 1, 6, -1, 14, -3, 2, -3, 5, -30, 19, -13, -9, -11, -5, -6, -7, -1, -14, -5, -13, -6, -9, -5, -11, 2, -2, 8, -15, -12, 7, -17, 1, 3, -1, -7, -7, -2, -7, 2, -2, 8, -4, -9, -1, 5, -10, -5, 0, 5, 3, 7, 2, -2, -5, -3, 0, 11, 0, -3, 1, -5, 2, 11, 4, -8, -12, 13, -1, 4, 0, -1, -1, 7, 5, -6, 6, 4, 5, 7, 5, 
  -4, -1, -4, -5, -4, -3, -1, 3, -3, 0, -4, -2, -4, 0, 0, -1, -4, 0, 8, -3, -7, -7, -7, 1, 7, 2, 5, 3, 1, 9, 3, 3, 8, 0, 5, -1, 10, -5, -4, -2, 6, 5, 0, 2, 4, -2, 0, 0, 3, 6, 7, 3, 5, 2, 10, 1, -4, -5, 3, 3, 4, -1, 6, -1, 1, 2, 1, 6, 7, 5, 7, 1, 9, -7, -8, -6, -5, 2, 5, 2, -1, 4, 0, 6, 2, -1, 3, 2, 7, 2, 9, -2, -7, -2, -1, 4, 4, 6, 4, 8, 3, 6, 9, 1, 6, 5, 10, 0, 10, 1, -6, -5, 3, 8, 9, 5, 7, 0, 6, 1, -2, 8, 0, 5, 4, 10, 8, -5, -6, -7, 0, 6, 0, 2, 5, 10, 7, 0, 9, 10, 7, 4, 4, 1, 
  -10, -9, 4, -16, -8, -6, 4, 23, 1, 8, 5, 8, 7, 18, 16, 2, -1, 1, 15, -9, 0, -13, 6, 17, 1, 4, 26, -3, 21, 9, 17, -3, 5, 3, -2, 16, 3, -60, 14, -6, 15, -1, -6, -8, -8, -10, 15, -9, -3, -6, -7, 9, -11, 6, 2, -18, -17, 22, -5, 4, 0, 13, 26, 1, 17, 13, 0, 23, -1, 2, 9, 20, -17, 63, -17, 45, 57, 16, 8, -6, 11, 9, -1, 2, -6, -7, 8, 2, -8, -12, 8, 15, -11, -8, -9, -19, -12, -11, -13, -5, -12, -11, -7, -8, 3, -6, -7, -7, 9, -19, 19, -6, 2, -12, 0, -4, 3, -7, -9, -4, -9, -2, -8, 0, -3, -6, 11, -22, -11, -24, 17, -10, -5, 2, 3, 3, -10, -2, 2, 6, 1, 2, -6, -7, 
  18, -4, -3, 22, 11, -6, -5, -1, -11, 7, -9, 7, -9, 0, -11, -11, -8, -12, 8, 36, 1, 2, 17, -7, -8, 3, -8, -4, -12, -7, -4, 2, -4, -11, -8, -12, 16, 14, -15, 6, -4, 2, 13, 15, 2, -3, -2, -8, -7, 4, -9, -4, -3, 0, 12, 31, 11, -8, -1, -15, -12, -11, -4, -13, -4, -7, -8, -12, -11, 1, -12, -4, 26, 1, 22, -28, -35, 5, -5, 4, 15, -6, 5, 0, 0, -6, 5, 3, 7, 0, 10, -73, -2, 0, -10, 3, 1, -3, 3, 11, 0, 8, 3, -4, 1, -2, -2, -7, 15, -18, -33, -1, 47, 6, 8, -3, 7, 0, -3, 2, 0, 3, -2, -7, 0, 1, 8, 4, -3, 15, 8, -1, -1, 0, -6, 5, -1, -1, 1, 0, -2, 5, 4, 4, 
  -3, 8, -4, -7, -3, 10, 5, 2, 5, 5, 6, 10, 9, 3, 7, 3, 9, 3, 14, 4, -3, -4, 4, 7, 9, 9, 9, 4, 10, -1, 8, -2, 3, 4, -1, 2, 6, 1, -8, -6, 3, 1, -2, 1, -1, 6, 2, 3, 1, 6, -2, -2, 12, 0, 11, -3, -5, -5, -3, 2, 11, 3, 12, 2, 5, -1, 13, 12, 10, 2, 2, 3, 8, -4, -7, -8, 5, 2, 1, 12, 1, 1, 0, 2, 12, 6, 4, 8, 10, 9, 10, -5, -10, -7, -1, 2, 9, 5, 6, -1, -2, -1, 0, 6, 4, 8, 1, 4, 11, -2, -6, -3, -3, 6, 9, 10, 5, -1, 9, 1, 8, 9, 3, 1, 7, -3, 11, 0, -11, -3, -5, 9, -3, 1, -1, 3, -2, 9, 5, 9, 9, 3, 8, 0, 
  13, 40, -27, 18, -7, 3, -12, -8, -5, -10, -8, -10, -10, -4, -9, 9, -2, 6, 14, 44, -20, 45, 7, 3, 3, 0, -3, -2, -5, -2, -7, -5, -10, -4, 1, -3, 25, 127, -18, 29, -12, 4, -4, 3, -1, -5, 8, 7, 8, -4, 5, 11, -6, -7, 16, 9, 14, -2, -3, -8, -17, -15, -13, -1, -5, -8, -14, -10, -13, -5, -11, -1, 50, -33, 22, -19, 8, -3, -8, 7, 8, 14, -2, -1, -3, 9, -2, -2, 5, 1, 15, 13, 4, -4, 22, 12, 3, -5, -3, -1, 9, -3, -3, 0, 5, 2, -4, -2, 15, 33, 0, -14, -16, -4, 5, 4, 6, 4, 5, 3, 6, -7, -5, 5, -5, 3, 16, 31, -13, 18, -13, -3, -1, -2, -5, 5, 7, 2, 2, -5, 6, -6, 3, -3, 
  1, -1, 1, -6, -4, -3, 4, 0, -1, 2, -4, 2, 2, -5, 4, -4, -1, 0, 11, -2, -4, -2, -5, 11, 12, 0, -2, -1, 10, 9, -6, -5, -5, 0, 14, 12, 8, -6, -4, -1, -2, 0, 1, -1, -1, 9, 2, -5, 8, 5, -1, -3, 0, 1, 11, -2, -5, -3, -3, 0, 4, 5, 9, 9, 4, -6, -5, 6, 7, 4, 11, 2, 8, -6, -3, 1, -2, -3, 6, 13, -2, -4, 4, -4, -2, 9, -2, 4, -2, -2, 9, 1, -2, -4, -5, 2, -3, 5, -6, 6, 11, 7, 6, 5, 6, -3, 2, -7, 12, 1, -4, -1, -2, 6, -7, 3, -1, 12, -2, -3, -3, -6, -4, -5, 11, 6, 6, -1, -1, -5, 0, -2, -5, -7, 4, 4, 1, -6, 13, 7, -2, -5, -2, 4, 
  -6, -3, -2, -7, -5, -5, 1, -3, 0, -3, 1, 1, 0, 1, -3, 0, -3, -3, 10, -5, -6, -7, -2, 3, 4, 4, 5, 4, 7, 4, 2, 2, 3, 1, 4, 2, 4, -6, -5, -4, -3, 6, 6, 2, 0, 1, 3, 4, -1, 2, -1, 5, 3, 4, 9, 27, -5, -7, -3, -1, 5, 4, 1, 0, 3, 3, 3, 0, 0, 0, -2, 1, 3, 0, -4, -5, -5, 4, 2, 1, 2, 3, -3, -1, -3, -3, -2, 2, 0, 4, 9, -5, -8, -9, -6, 7, 7, 8, 4, 3, 4, 4, 9, 8, 8, 7, 5, 9, 8, -7, -8, -5, 1, 6, 0, 1, 0, 5, 7, 6, 9, 9, 5, 3, 4, 3, 6, -9, -1, -4, -8, 7, 6, 3, 0, 5, 1, 8, 2, 7, 4, 5, 4, 6, 
  -5, 17, -23, -13, -26, 0, 1, -1, 1, 10, 3, 1, 8, 13, 3, 13, 9, 6, 12, 33, -20, -4, -8, 6, 5, 1, 4, 0, 7, 2, 0, 5, -2, 9, 7, 7, 17, -46, -21, 4, 10, 6, -1, 1, 1, 4, 13, 10, 4, 12, 9, 0, 0, 6, 6, 22, -7, -1, 7, 4, -2, -3, -1, 7, 4, 5, 7, 4, 2, 6, 1, -1, 18, 21, -7, -10, 4, 10, 0, 1, 8, 10, 14, 12, 15, 12, 1, 3, 5, 5, 7, 1, -11, -15, 15, -1, 6, 4, 8, 3, 0, 7, 7, 6, 4, -1, 4, 8, 12, -33, -19, -16, 11, 0, -2, 4, 1, 2, 8, 7, 6, 2, 5, 1, 5, 6, 6, -38, -7, -4, 1, 7, 9, 3, 5, 9, 6, 4, 7, 10, 7, 4, 8, 1, 
  6, 2, -1, -3, -43, 3, -16, 12, -12, -1, -7, 0, 7, 1, -9, -11, -14, -11, 8, 16, -15, -1, -2, -10, -10, -14, -12, 5, -7, -5, -3, -13, -11, -13, -6, -3, 20, -68, -19, 23, 93, 7, 14, -6, 13, -6, -4, 7, 14, 8, 0, 5, -7, -3, 15, 86, 49, 1, 25, -9, -7, -11, -8, -15, 0, 2, 2, 2, -6, 4, -15, -9, 27, -8, 9, -23, -38, -6, 5, -8, -5, 6, -6, -5, 6, 2, 11, 12, -3, -9, 12, -26, -20, 24, -6, 0, 0, 17, 4, -2, 5, 14, 6, -4, -3, 6, 3, -1, 10, -28, -35, 11, 80, 8, -4, 8, 9, -2, 8, -6, 3, -1, -3, -2, 10, 1, 8, -80, 24, 48, 52, -6, 3, -1, -7, -7, 6, -2, -2, 14, 12, 0, 7, -9, 
  3, -7, -4, 0, 1, -4, -4, 2, 4, 2, 9, -6, -5, 9, -6, -3, -5, 1, 11, -7, 1, 2, -4, 11, -6, -3, 0, -5, 12, -1, 15, -3, -2, 9, 0, -4, 5, -3, 4, -6, -7, 12, -6, 9, 0, 9, -2, -3, -6, -2, 0, 7, 5, 0, 5, -5, 5, -3, 1, -3, 2, 6, -3, 12, 3, 12, 12, 9, -1, 7, 2, -3, 11, -7, 4, 0, -6, 4, 1, 2, 8, 2, -4, -2, 3, -4, 10, 2, -5, 3, 7, 2, -1, 0, -8, 1, 11, 11, 12, 15, -6, 14, -4, 10, -6, -1, 8, -6, 7, 0, -2, -2, 2, 6, -6, 8, 15, -6, 11, 12, -3, 0, 1, -4, -4, -5, 9, 5, 5, -6, -2, -4, 1, 1, 10, 7, 13, 6, -5, 12, -1, 5, -1, -3, 
  -9, -2, -8, -13, 17, 5, 3, 4, 4, 4, 3, 5, 1, 4, 5, 5, 4, 5, 8, -5, -9, -7, 10, 10, 9, 7, 5, 6, 7, 5, 9, 5, 6, 10, 7, 9, 3, 31, 1, -7, 11, 4, 8, 2, 9, 3, 2, 4, 3, 9, 8, 5, 9, 11, 4, -8, -6, -6, 12, 13, 9, 5, 9, 5, 8, 9, 8, 4, 8, 11, 4, 13, -2, 2, -9, -4, 8, 6, 9, 5, 0, 1, 4, 7, 8, 7, 4, 6, 7, 10, 7, 41, -8, -4, 68, 10, 2, 9, 9, 9, 10, 11, 11, 5, 10, 4, 7, 10, 10, 54, 0, -11, -1, 9, 11, 4, 6, 3, 8, 7, 5, 9, 7, 6, 10, 7, 5, -8, -9, -12, -1, 6, 9, 12, 4, 5, 5, 5, 8, 8, 5, 9, 5, 8, 
  -19, -19, 17, -17, 9, 4, 4, -3, 14, -8, -7, 3, 11, 13, 1, 9, -8, -2, 13, -26, 4, -23, 9, 2, 14, 2, 4, 20, -1, 19, 11, 5, 20, -1, 2, 1, 2, -56, 28, -20, 14, -6, -3, 2, -7, -12, 9, -13, -4, -9, -1, -5, -6, -10, 0, -25, -22, 7, 3, 2, 3, 34, 3, 11, -1, 19, 13, 6, 10, 33, -2, 1, -25, 70, -17, 42, 43, 3, -9, 1, -2, 12, -14, -9, -3, 7, -5, -10, 13, -10, 12, 44, -1, -15, -7, -17, -9, -10, 1, -10, -10, -8, -11, -9, 1, 1, -3, 8, 10, 6, 39, -10, 1, -12, -9, 1, -5, 6, -7, -8, 0, -5, -6, -1, 13, 2, 10, -30, 6, -12, -1, 5, -6, -1, -9, -5, 3, -12, 6, -13, 7, -5, 3, -2, 
  -4, -2, -2, -2, -2, -3, -3, 1, -1, -2, -3, 1, -3, 0, -4, -3, -4, -1, 12, -4, -3, -6, -7, 8, 0, -1, 0, 4, 2, 0, 2, -1, 3, 4, 3, 8, 12, -4, -1, -6, -3, 1, 8, 1, 4, -1, 3, 8, -1, 5, 0, 0, 8, 6, 9, -4, -2, -7, 3, 0, 3, -2, 4, 5, 0, 4, 1, 1, 3, 0, 5, 0, 10, -1, -3, -2, -7, -1, 5, -2, -2, -2, -2, 2, 3, 5, 0, 2, 2, 4, 9, -1, -7, -5, 2, 7, 6, 1, 10, -2, 10, 6, 4, 0, 0, -3, -1, 10, 10, -7, -7, -6, -2, 4, -1, 5, 8, 10, 1, 3, 0, 10, 5, 9, 4, 6, 10, 2, -2, -1, -3, 6, 0, 8, 4, 2, 10, 7, 5, 2, -2, -2, -2, 8, 
  20, 45, -27, -1, 17, 1, -10, -9, 3, -5, -8, -8, -8, -5, -9, -3, 3, -1, 9, 111, -28, 53, 17, 4, -8, -10, -2, -5, -10, -10, 0, -5, -9, -10, 6, 2, 26, 55, -18, 19, -26, 1, -7, 2, 2, 2, 16, 6, -6, -6, 2, -6, 4, -6, 23, -7, -17, -1, -7, -5, -15, -16, -13, 2, 0, -9, 2, -14, -8, 1, -2, -3, 49, -33, -1, 15, 34, 0, -4, 3, 6, 6, 17, 3, 9, 2, 12, 2, 0, -10, 7, 64, 19, -16, 22, -6, 4, 1, 9, -4, -7, 8, 3, 1, -2, 0, -3, -5, 14, 45, -5, -15, -32, -8, -9, -10, 1, 1, -9, -8, 4, -7, -5, -1, 0, 7, 12, 16, -11, 4, -22, -3, 0, -2, -2, -5, -1, 9, -6, 2, 4, -6, -3, -7, 
  -5, 12, 1, -5, 14, -2, 1, -2, 6, 6, -5, 7, 6, 0, 0, -3, 0, -5, 7, 9, -1, -6, 26, -5, 1, 2, -4, -2, 4, 11, -4, 3, 11, -4, 2, 4, 6, -4, -1, -3, -5, -4, 5, 10, 2, -4, -5, 6, 1, 2, 6, 8, -5, 6, 11, -4, 0, -6, -6, 11, -4, 8, -4, 5, -4, 0, 0, -3, -4, -3, -5, 9, 8, -2, -3, -2, -6, -6, -5, -2, 11, 1, 1, -4, 0, 5, 12, 0, 5, 1, 5, 2, -5, -3, -3, -6, -5, -5, 16, -4, -1, 11, 9, -5, 0, 8, -7, -5, 9, -1, 2, 1, -3, -4, 6, 3, 1, -4, -2, 1, 15, 3, 6, -3, 5, 8, 5, -3, -4, -2, -3, 2, 12, 7, 3, 15, 6, 12, -3, -2, 5, -4, 5, 4, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,144 } };
const TfArray<1, float> quant6_scale = { 1, { 0.016596183180809021, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.12996840476989746, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.067022763192653656, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.059617795050144196, } };
const TfArray<1, int> quant9_zero = { 1, { 127 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2880, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_858858_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_858858_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_858858_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_858858_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_858858_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
